- pyeasee/site.py
Add name property to get better consistency on how name information can be accessed between charger, site and equalizer.
> Add name property to site and equalizer

- pyeasee/charger.py
- pyeasee/easee.py
- tests/test_charger.py
- tests/test_client.py
add status with the status string, raw access to chargerOpmode is now possible.
This will be a breaking change but i think the status codes are better, especially with the updated reason for no current as you get more info about that is happening. 
I also wanted to not overwrite the chargerOpmode so this is still a int and status is the string.
> Update status codes and

- pyeasee/charger.py
- pyeasee/site.py
- tests/test_client.py
Added raw mode that presents raw data from the api. Except for the little change that None in Reason_for_no_current is changed to string "none".
The intention is that this PR is fully backwards compatible. CLI tools and current release of easee are not affected.
Text mappings in pyeasee are not changed. 
My idea is to map integer values to translatable strings in easee.
I think this PR can be merged and released to pypi after review. It will simplify further development in easee if the library is available as a new release.
> Add raw mode, backwards compatible

- pyeasee/charger.py
Fix smart_charging() method and add bool to turn on or off. Original API call to /api/chargers/{id}/commands/smart_charging was believed to be a toggle, but updated docs says it is only to turn on and that settings must be used to turn off: «Turn off smart charging again by posting an explicit value to the charger settings endpoint».
So to summarize, why not use call to /api/chargers/{id}/settings to turn both on and off. Tested to be working with HA switch as well.
> Fix smart_charging()

- setup.py
signalrcore 0.8.9 has breaking changes, so pinning 0.8.8 lib version for now.
> Pin version 0.8.8 of signalrcore lib

- pyeasee/const.py
- requirements-dev.txt
- setup.py
Adding requirement to use 0.57.0 version of websocket because of incompatibility with signalrcore lib in later version.
Correcting names for offline mode current limits.
> Pin websocket version

- pyeasee/easee.py
Stop relying on signalcore lib internal retries when disconnected from server and instead restart the connection process.
Catch authentication errors when connecting to signalr server and try to refresh token if it fails.
Bug in _refresh_token function fixed.
User-Agent added.
.send() now called from a thread due to potentially blocking.
> Improved authentication and retry for signalr connection

- html/pyeasee/charger.html
- html/pyeasee/site.html
- pyeasee/charger.py
- pyeasee/site.py
Updated code for how to set dynamic current limit on circuit level. Affects two methods:
**Charger.set_dynamic_charger_circuit_current**
New optional parameter, timeToLive has been added.
**Circuit.set_dynamic_current**
New optional parameter, timeToLive has been added.
timeToLive specifies, in minutes, the validity of the new current limit.
If timeToLive is set to zero, then the setting is valid until the next time it is changed, or the charger is restarted. This call is used: https://api.easee.cloud/api/sites/siteId/circuits/circuitId/dynamicCurrent
If timeToLive is omitted, then the old code will be executed. This means that the new current limit will be valid until the next time it is changed, a new charging sessions starts, or the charger is restarted, whichever comes first.
API …
> Charger.set_dynamic_charger_circuit_current extended 

- pyeasee/utils.py
The format returned from the Easee API may have a varying number of fractional second digits, this change aims to solve that by ignoring the fractions completely.
> Changed datetime parsing

- pyeasee/easee.py
When a token has expired a new token is requested with the token_refresh API.
However, the request headers were not updated with the new token after the call.
Also, a custom header is added to the login and token_refresh API calls.
> Move header update after token refresh

- requirements-dev.txt
- setup.py
(and removed workaround dependancy for websocket-client)
Since there is not anymore any dependance on old versions of webscocket-client in Home Assistant signalrcore can now be updated to latest version.
> Upgrading signalrcore to 0.9.5

- pyeasee/charger.py
- pyeasee/easee.py
Added a new function get_account_products() to retrieve all sites/products that are accessible by the currently logged in user. This is in contrast to the existing get_sites() function which retrieves also products that are not accessible.
Changed the lockCablePermanently() function to use /api/chargers/{id}/commands/lock_state instead because it seems the old method does not work when the user does not have rights to change settings on the charger.
> Changes to better support large installation sites.

- pyeasee/easee.py
When the new function get_account_products() it was not noted that it in turn calls another API to gather more details.
This means that the information from the products API gets lost.
This should solve that by copying that information back in to the site structure.
> Additional changes to get_account_products

- pyeasee/easee.py
- pyeasee/exceptions.py
- pyeasee/site.py
403 - Forbidden is returned when a user has insufficient privileges to execute the service. 
It happens typically if the user is a `site_user` and attempts to execute a restricted service.
400 - Bad request is used a catch-all for invalid arguments and operation not allowed.
> More fine-grained exception handling

- pyeasee/easee.py
Easee are switching to new servers for SignalR, the URL needs to be changed.
> URL for SignalR changed

- .gitignore
- pyeasee/charger.py
- pyeasee/easee.py
- pyeasee/site.py
- tests/test_client.py
Easee is switching their entire API to the new .com domain
https://developer.easee.cloud/docs
> We are implementing a series of internal modifications to enhance performance and reliability. As part of this process, we have updated the base API URL from api.easee.cloud to api.easee.com.
The api.easee.cloud domain will reach its end of life on September 1st 2023. The api.easee.com domain is already active and we recommend users to update the URL at the earliest convenience.
Please note that this change primarily affects our internal systems, so the only modification required on your end is to update the URL used to connect to our APIs. The endpoints on this page will soon be updated to mirror the modifications.
> Switch to new Easee API domain

- pyeasee/charger.py
poll_lifetimeenergy and poll_chargeropmode is available in the API but was not implemented in the client.
> Add poll energy and opmode to charger

- pyeasee/charger.py
Easee.get_chargers API call does not return userRole (at least on my user). This code will set userRole to -1 if missing in API-call.
> Bugfix: Handle missing userRole for chargers

- pyeasee/easee.py
The signalr lib seems to retry in an endless loop when it fails to negotiate the initial connection.
It does however seem to change the status from connecting to disconnected when this happens so we should get a callback.
This patch tries to work around that by cancelling the signalr task when that happens, and then restart it after a delay.
> SignalR lib reconnect issue workaround

- pyeasee/easee.py
A watchdog that watches over the connection process of signalr and triggers a restart of the signalr task if it seems to have failed to connect.
> SignalR watchdog added

- pyeasee/easee.py
- setup.py
The websocket error handling in pysignalr is overridden with a version of the code that allows all exceptions to propagate further.
The watchdog is not needed anymore so it has been removed.
> Override of error handling in pysignalr

- examples/user_consumption.py
- pyeasee/site.py
New site functions that can retrieve information regarding users connected to the site, and a users monthly or yearly consumption data.
An example using the function also added.
> Add functions to retreive users and consumption per user

- pyeasee/const.py
- pyeasee/easee.py
- setup.py
Change to pysignalr 1.1.0.
Add ssl context to init of pysignalr.
> Prepare for release of pysignalr 1.1.0

- pyeasee/easee.py
WIP:
Add throttler context to requests. The limits are set when initiating the Easee class.
No 429 handler yet.
> Add throttler context to requests

- pyeasee/__init__.py
- pyeasee/easee.py
- pyeasee/site.py
- pyeasee/throttler.py
Enforce throttling on specific APIs. 
Add retry-after argument to 429 exception.
Move throttler to separate file.
Improved throttling mechanism matching Easee API retry-after times.
> Throttling and 429.

- examples/site_consumption.py
- pyeasee/charger.py
Including example to download the full hourly consumption from a site
Tested on a site with ~100 chargers. Managed to download 2025 YTD. 2024 failed partway through due to too many requests, so you may have to adjust the example
See issue #33
> Add wrapper for hourly consumption endpoint
