Makefile
easee/__init__.py
easee/__main__.py
easee/charger.py
easee/easee.py
easee/site.py
easee/utils.py
html/easee/charger.html

- remove cached state for state and config in Charger
- Added line length 120 to black
- Add more targets to Makefile
- Make it pass flake8

Remove cached state

---

easee/site.py
html/easee/site.html

To be able to set the dynamic current of a circuit, I added a method to the Circuit class.
To make this work, the Circuit needs to know the id of the site it belongs to, so this was added as a parameter, site_id, at the creation of the object.

Add function to set dynamic current of a circuit

---

easee/__main__.py
easee/site.py
html/easee/site.html
html/easee/utils.html

Rudimentary support for Equalizers added.
Support for finding (site->get_equalizers)
And support for getting state (equalizer->get_state)

Add support for Equalizers

---

pyeasee/charger.py
pyeasee/site.py

Methods on charger- and circuit level to set offline current.

Methods to set offline current

---

pyeasee/__main__.py

This update creates a separate sync main function that can be called from a sync script and renames the old async version to async_main.

Fix 'coroutine 'main' was never awaited' message when run from CLI

---

pyeasee/charger.py
pyeasee/easee.py
pyeasee/site.py

Add await statement to fix a bug.
try clauses added in several locations to catch server errors (50x) in a better way.

await added to fix error message, better error handling

---

pyeasee/easee.py

Subtracting a minute from token expiration time to solve race condition between lib and server.

Token expiration time

---

pyeasee/charger.py

The return data from the weekly schedule API has changed which made the lib incompatible.

Weekly schedule bugfix

---

pyeasee/__main__.py
pyeasee/charger.py
pyeasee/const.py
pyeasee/easee.py
pyeasee/site.py

Renaming a few observations to allow them to be collected by HA integration.
Added site cost API.

New observations

---

README.md

The example is updated and verified to work.

Updated example in readme

---

pyeasee/utils.py

The signalr stream transfers boolean values in a number of different ways, this patch changes the interpretation such that it works with more variants.

Changed the interpretation of bool values in signalr stream

---

Makefile
requirements-dev.txt
setup.cfg

Update dev tools and parameters

---

pyeasee/const.py

state_eqAvailableCurrentP1/2/3 were incorrectly defined. Also adding a couple of new state data.

Fix for state_eqAvailableCurrentPx

---

pyeasee/charger.py

Changes needed to allow for chargeStopTime an optional argument.

Make chargeStopTime optional

---

pyeasee/easee.py

A bit of leftover code after changing signalr lib was causing unnecessary reconnects.

Improvements to SignalR connection logic

---

pyeasee/site.py

Preliminary functions for solar charging settings

Prototype for solar charging settings

---

pyeasee/charger.py
pyeasee/const.py
pyeasee/site.py

A bugfix for surplus charging function.
New functions to enable and disable charge plans.

Fixes for surplus charing + functions to enable and disable charge plans

---

pyeasee/easee.py

Watchdog now watches if there is data coming and and if nothing is received within 300 seconds the signalr task is restarted.

Watchdog changed to watch recieved data instead

---

pyeasee/__init__.py

Add version info __version__ string

---

pyeasee/charger.py

Add API for LED strip brightness

Add API for LED strip brightness

---

pyeasee/charger.py

Some more throttlers to avoid API 429 return values added.

Added throttlers
